using static MeuSuporte.Class_RemoveBloatware;

namespace MeuSuporte
{
    internal class Class_ListBloatware
    {
        public Bloatware[] List = {
            new Bloatware { Titulo = "Clima", Comando = "Weather" },
            new Bloatware { Titulo = "3D Builder", Comando = "Microsoft3DViewer" },          
            new Bloatware { Titulo = "Alarmes", Comando = "WindowsAlarms" },
            new Bloatware { Titulo = "Obter o Office", Comando = "MicrosoftOfficeHub" },
            new Bloatware { Titulo = "Obter o Skype", Comando = "SkypeApp" },
            new Bloatware { Titulo = "Email e Calendário", Comando = "windowscommunicationsapps" },
            new Bloatware { Titulo = "Mapas", Comando = "WindowsMaps" },
            new Bloatware { Titulo = "Mapas", Comando = "BingMaps" },
            new Bloatware { Titulo = "Dinheiro", Comando = "BingFinance" },
            new Bloatware { Titulo = "Música Groove", Comando = "ZuneMusic" },
            new Bloatware { Titulo = "OneNote", Comando = "OneNote" },
            new Bloatware { Titulo = "Phone Companion", Comando = "CommsPhone" },
            new Bloatware { Titulo = "Solitário", Comando = "MicrosoftSolitaireCollection" },
            new Bloatware { Titulo = "Esportes", Comando = "BingSports" },
            new Bloatware { Titulo = "Gravador de voz", Comando = "WindowsSoundRecorder" },
            new Bloatware { Titulo = "Xbox", Comando = "XboxApp" },
            new Bloatware { Titulo = "Xbox Game Bar", Comando = "XboxGamingOverlay" },
            new Bloatware { Titulo = "Microsoft To Do", Comando = "Todos_8wekyb3d8bbwe" },
            new Bloatware { Titulo = "Notas autoadesivas", Comando = "MicrosoftStickyNotes" },
            new Bloatware { Titulo = "Microsoft 365 (Hub)	", Comando = "MicrosoftOfficeHub" },
            new Bloatware { Titulo = "Cortana	", Comando = "549981C3F5F10" },
            new Bloatware { Titulo = "Copilot	", Comando = "MicrosoftWindows.Client.WebExperience" },
            new Bloatware { Titulo = "Teams ", Comando = "MicrosoftTeams" },
            new Bloatware { Titulo = "Teams ", Comando = "TeamsFree" },
            new Bloatware { Titulo = "TikTok", Comando = "TikTok" },
            new Bloatware { Titulo = "Instagram", Comando = "InstagramBeta" },
            new Bloatware { Titulo = "Facebook", Comando = "Facebook" },
            new Bloatware { Titulo = "Twitter", Comando = "Twitter" },
            new Bloatware { Titulo = "Dicas", Comando = "GetHelp" },
            
            new Bloatware { Titulo = "Mensagens", Comando = "Messaging" },

            new Bloatware { Titulo = "Feedback Hub", Comando = "WindowsFeedbackHub" },
            new Bloatware { Titulo = "OneConnect", Comando = "OneConnect" },
            new Bloatware { Titulo = "Speed Test", Comando = "NetworkSpeedTest" },
            new Bloatware { Titulo = "Office Sway", Comando = "Office" },
            new Bloatware { Titulo = "Office Sway", Comando = "Sway" },
            new Bloatware { Titulo = "Adobe Express", Comando = "AdobeSystemsIncorporated" },
            new Bloatware { Titulo = "Adobe Express", Comando = "AdobeExpress" },
            new Bloatware { Titulo = "Prime Video", Comando = "AmazonVideo" },
            new Bloatware { Titulo = "Prime Video", Comando = "PrimeVideo" },
            new Bloatware { Titulo = "Prime Video", Comando = "AmazonVideo" },
            new Bloatware { Titulo = "Roblox", Comando = "ROBLOX" },
            new Bloatware { Titulo = "Roblox", Comando = "ROBLOXCORPORATION" },
            new Bloatware { Titulo = "Email e Calendário", Comando = "windowscommunicationsapps" },
            new Bloatware { Titulo = "Spotify", Comando = "SpotifyMusic" },
            new Bloatware { Titulo = "Spotify", Comando = "SpotifyAB" },
            new Bloatware { Titulo = "LinkedIn", Comando = "LinkedIn" },
            new Bloatware { Titulo = "Candy Crush Saga", Comando = "CandyCrushSaga" },
            new Bloatware { Titulo = "Bubble Witch 3", Comando = "BubbleWitch3Saga" },
            new Bloatware { Titulo = "March of Empires", Comando = "Gameloft" },
            new Bloatware { Titulo = "March of Empires", Comando = "MarchofEmpires" },
            new Bloatware { Titulo = "Disney Magic Kingdoms", Comando = "Disney" },
            new Bloatware { Titulo = "Hidden City Hidden Object Adventure", Comando = "HiddenCityMysteryofShadows" },
            new Bloatware { Titulo = "Hidden City Hidden Object Adventure", Comando = "G5Entertainment" },
            new Bloatware { Titulo = "Age of Empires Castle Siege", Comando = "AgeofEmpiresCastleSiege" },
            new Bloatware { Titulo = "Asphalt 8", Comando = "Asphalt8Airborne" },
            new Bloatware { Titulo = "Candy Crush Friends Saga", Comando = "CandyCrushFriends" },
            new Bloatware { Titulo = "Bubble Witch 3 Saga", Comando = "BubbleWitch3Saga" },
            new Bloatware { Titulo = "Astro", Comando = "Astro" },
            new Bloatware { Titulo = "Earbuds", Comando = "Earbuds" },
            new Bloatware { Titulo = "Earbuds", Comando = "Samsung" },
            new Bloatware { Titulo = "McAfee", Comando = "McAfee" },
            new Bloatware { Titulo = "Gerenciador de Telefone", Comando = "YourPhone" },
            new Bloatware { Titulo = "Visualizador 3D", Comando = "MixedReality" },
            new Bloatware { Titulo = "Visualizador 3D", Comando = "Viewer" },
            new Bloatware { Titulo = "Assistência Rápida", Comando = "QuickAssist" },
            new Bloatware { Titulo = "Windows Media Player", Comando = "WindowsMediaPlayer" },
            new Bloatware { Titulo = "Power Automate Desktop", Comando = "PowerAutomateDesktop" },
            new Bloatware { Titulo = "Whiteboard", Comando = "Whiteboard" },
            new Bloatware { Titulo = "Xbox Game Speech Window", Comando = "XboxSpeechToTextOverlay" },
            new Bloatware { Titulo = "Xbox Identity Provider", Comando = "XboxIdentityProvider" },
            new Bloatware { Titulo = "Realidade Misturada Portal", Comando = "MixedReality" },
            new Bloatware { Titulo = "Amazon Appstore", Comando = "AmazonAppstore" },
            new Bloatware { Titulo = "Amazon Appstore", Comando = "Amazon" }
        };
    }
}
